# Config file for various conversion technologies.
wind_onshore:
  converter_IV: 'V110'
  converter_III: 'V90'
  converter_II: 'V117'
  converter_I: 'V164'
  resource: 'wind'
  deployment: 'onshore'
  resource_threshold: 5. #m/s
  population_density_threshold_low: 0.
  population_density_threshold_high: 100.
  protected_areas_selection: ['Ia', 'Ib', 'II']
  protected_areas_distance_threshold: 10.
  depth_threshold_low: 0.
  depth_threshold_high: 0.
  altitude_threshold: 1500.
  terrain_slope_threshold: 0.03
  forestry_ratio_threshold: 0.7
  legacy_min_capacity: 0.2

wind_offshore:
  converter_IV: 'V110'
  converter_III: 'V90'
  converter_II: 'V117'
  converter_I: 'V164'
  resource: 'wind'
  deployment: 'offshore'
  resource_threshold: 7. #m/s
  population_density_threshold_low: 0.
  population_density_threshold_high: 100.
  protected_areas_selection: ['Ia', 'Ib', 'II', 'V']
  protected_areas_distance_threshold: 5.
  depth_threshold_low: 5.
  depth_threshold_high: 59.
  altitude_threshold: 0.
  terrain_slope_threshold: 1.
  forestry_ratio_threshold: 1.
  legacy_min_capacity: 0.5

wind_floating:
  converter: 'E-126'
  resource: 'wind'
  deployment: 'floating'
  resource_threshold: 9. #m/s
  population_density_threshold_low: 0.
  population_density_threshold_high: 100.
  protected_areas_selection: ['Ia', 'Ib', 'II', 'V']
  protected_areas_distance_threshold: 5.
  depth_threshold_low: 60.
  depth_threshold_high: 999.
  altitude_threshold: 0.
  terrain_slope_threshold: 1.
  forestry_ratio_threshold: 1.

pv_utility:
  converter: 'DEG15MC'
  resource: 'pv'
  deployment: 'utility'
  resource_threshold: 130. #W/m2
  population_density_threshold_low: 0.
  population_density_threshold_high: 100.
  protected_areas_selection: ['Ia', 'Ib', 'II', 'V']
  protected_areas_distance_threshold: 5.
  depth_threshold_low: 0.
  depth_threshold_high: 0.
  altitude_threshold: 2000.
  terrain_slope_threshold: 0.05
  forestry_ratio_threshold: 0.8
  legacy_min_capacity: 0.05

pv_residential:
  converter: 'DD06M'
  resource: 'pv'
  deployment: 'residential'
  resource_threshold: 100. #W/m2
  population_density_threshold_low: 10.
  population_density_threshold_high: 999999.
  protected_areas_selection: ['Ia', 'Ib', 'II', 'V']
  protected_areas_distance_threshold: 1.
  depth_threshold_low: 0.
  depth_threshold_high: 0.
  altitude_threshold: 3000.
  terrain_slope_threshold: 1.
  forestry_ratio_threshold: 1.
  legacy_min_capacity: 0.001

