# Spatial resolution (in degrees) of the potential sites.
spatial_resolution: 0.5

# Various data layers to be taken into account in potential site selection.
filtering_layers:
  resource_quality: True
  population_density: True
  protected_areas: False
  bathymetry: True
  orography: True
  forestry: True
  water_mask: True

time_slice: ['2015-01-01T00:00', '2015-01-01T12:00']
regions: ['BE']
technologies: ['wind_onshore', 'wind_offshore', 'pv_utility', 'pv_residential']


modelling: 'pyomo' # Choice of modelling language
solver: 'gurobi' # Choice of solver. Available: 'gurobi' and 'cplex' and 'cbc'
solver_options:
  gurobi:
    Threads: 0
    Crossover: 0
  cplex: 0
  cbc: 0

# Type of problem to be solved. Check resite.py for a full list.
formulation: 'meet_RES_targets_year_round' # 'meet_RES_targets_hourly' # 'meet_demand_with_capacity' #

# List of deployments per region (ordered as the 'regions' list above)
deployment_vector: [0.1] # [0.5, 0.5, 0.5, 0.5]

# Keeping files at the end of the run.
keep_files: False
