# Spatial resolution (in degrees) of the potential sites.
spatial_resolution: 0.5

# Various data layers to be taken into account in potential site selection.
filtering_layers:
  resource_quality: True
  population_density: True
  protected_areas: False
  bathymetry: True
  orography: True
  forestry: True
  water_mask: True

timeslice: ['2015-01-01T00:00', '2015-12-31T23:00']
regions: ['CWE']
technologies: ['wind_onshore', 'wind_offshore', 'pv_utility']

use_ex_cap: False

modelling: 'pyomo' # Choice of modelling language. Available: 'gurobipy', 'docplex' and 'pyomo'
solver: 'gurobi' # Choice of solver. Available: 'gurobi', 'cplex' and 'cbc'
solver_options:
  gurobi:
    Threads: 0
    Crossover: 0
  cplex: 0
  cbc: 0
write_lp: False
write_log: False

# Type of problem to be solved. Check resite.py for a full list.
formulation: 'meet_RES_targets_agg' # 'meet_RES_targets_hourly' # 'meet_RES_targets_agg' # 'meet_demand_with_capacity' #

# List of deployments per region (ordered as the 'regions' list above)
deployment_vector: [0.5] # [0.5, 0.5, 0.5, 0.5]

# Keeping files at the end of the run.
keep_files: True
