# Spatial resolution (in degrees) of the potential sites.
spatial_resolution: 0.5

# Various data layers to be taken into account in potential site selection.
resource_quality_layer: True
population_density_layer: True
protected_areas_layer: False
bathymetry_layer: True
orography_layer: True
forestry_layer: True
water_mask_layer: True
legacy_layer: True

time_slice: ['2015-01-01T00:00', '2015-01-01T12:00']
regions: ['BE']
technologies: ['wind_onshore', 'wind_offshore', 'solar_utility', 'solar_residential']

# Choice of solver. Available: 'gurobi' and 'cplex'.
solver: 'gurobi'

# Type of problem to be solved. Check models.py for a full list.
formulation: 'meet_demand_with_capacity' # 'meet_RES_targets_hourly', 'meet_RES_targets_year_round'

# List of deployments per region (ordered as the 'regions' list above)
deployment_vector: [1.0, 2.5, 2.0, 15.0]

# Keeping files at the end of the run.
keep_files: False
