spatial_resolution: 0.5
timeslice: ['2015-01-01T00:00', '2015-01-01T23:00']
regions: ['BENELUX']
technologies: ['wind_onshore']

use_ex_cap: False

modelling: 'pyomo' # Choice of modelling language. Available: 'gurobipy', 'docplex' and 'pyomo'
# solver: 'gurobi' # Choice of solver. Available: 'gurobi', 'cplex' and 'cbc'
write_lp: False

# Type of problem to be solved. Check resite.py for a full list.
formulation: 'meet_demand_with_capacity' # 'meet_RES_targets_hourly' # 'meet_RES_targets_agg'
formulation_params: [0.5, 0.5, 0.5, 0.5]
