# solver
solver:
  Crossover: 0

# Time
# Start time and end time for slicing the database.
time:
  slice: ['2015-01-01T00:00', '2015-7-01T23:00']
  resolution: 1

# Space
region: "EU"
add_offshore: True

# RES
res:
  include: True
  strategy: "bus" # (max or comp) or bus or no_siting or siting

  # For strategy = max or comp
  resite_nb: 100 # can be multiples of 25
  area_per_site: 2500 #km2
  cap_dens:
    wind: ""  # GW/km2
    pv: ""  # GW/km2

  # For strategy = full or generate
  # Various data layers to be taken into account in potential site selection.
  spatial_resolution: 0.5
  technologies: ['wind_onshore', 'wind_offshore', 'pv_utility', 'pv_residential']
  timeslice: ['2015-01-01T00:00', '2015-12-31T23:00']
  use_ex_cap: True
  filtering_layers:
    resource_quality: True
    population_density: True
    protected_areas: False
    bathymetry: True
    orography: True
    forestry: True
    water_mask: True

  # For strategy = generate
  modelling: 'pyomo' # Choice of modelling language. Available: 'gurobipy', 'docplex' and 'pyomo'
  solver: 'gurobi' # Choice of solver. Available: 'gurobi', 'cplex' and 'cbc'
  solver_options:
    gurobi:
      Threads: 0
      Crossover: 0
    cplex: 0
    cbc: 0
  write_lp: True
  # Type of problem to be solved. Check resite.py for a full list.
  formulation: 'meet_RES_targets_agg' # 'meet_RES_targets_hourly' # 'meet_demand_with_capacity' #
  # List of deployments per region (ordered as the 'regions' list above)
  deployment_vector: [0.1] # [0.5, 0.5, 0.5, 0.5]
  # Keeping files at the end of the run.
  keep_files: False

# Conventional generation
dispatch:
  include: True
  tech: "ccgt"

# Nuclear
nuclear:
  include: True
  use_ex_cap: True # Whether to include existing cap
  extendable: False

# Battery
battery:
  include: True
  type: "Li-ion E"
  max_hours: 4

# Hydro
phs:
  include: True
  use_ex_cap: True
  extendable: False
  cyclic_sof: True

ror:
  include: True
  use_ex_cap: True
  extendable: False

sto:
  include: True
  use_ex_cap: True
  extendable: False
  cyclic_sof: True

# Emissions
co2_emissions:
  global_per_year: 1 #Gt/year
  level_1990: 523.6 # t/GWh
  reduc_from_1990: 0.8 #%
