# solver
solver:
  Crossover: 0
  #threads: 4
  #method: 2 # barrier
  #crossover: 0
  #BarConvTol: 0.01
  #FeasibilityTol: 0.01
  #AggFill: 0
  #PreDual: 0
  #GURO_PAR_BARDENSETHRESH: 200

# Time
# Start time and end time for slicing the database.
time:
  slice: ['2015-01-01T00:00', '2015-01-01T23:00']
  resolution: 1

# Space
region: "BENELUX"

add_offshore: True

# RES
res:
  include: True
  strategy: "generate" # max or comp or asusual or bus or full or generate
  technologies: ['wind_onshore', 'wind_offshore', 'pv_utility', 'pv_residential']
  spatial_resolution: 0.5
  resite_nb: 100 # can be multiples of 25
  area_per_site: 2500 #km2
  use_ex_cap: False
  cap_dens:
    wind: ""  # GW/km2
    pv: ""  # GW/km2
  # Various data layers to be taken into account in potential site selection.
  filtering_layers:
    resource_quality: True
    population_density: True
    protected_areas: False
    bathymetry: True
    orography: True
    forestry: True
    water_mask: True
  timeslice: ['2015-01-01T00:00', '2015-12-31T23:00']

  modelling: 'pyomo' # Choice of modelling language. Available: 'gurobipy', 'docplex' and 'pyomo'
  solver: 'gurobi' # Choice of solver. Available: 'gurobi', 'cplex' and 'cbc'
  solver_options:
    gurobi:
      Threads: 0
      Crossover: 0
    cplex: 0
    cbc: 0
  write_lp: True

  # Type of problem to be solved. Check resite.py for a full list.
  formulation: 'meet_RES_targets_year_round' # 'meet_RES_targets_hourly' # 'meet_demand_with_capacity' #

  # List of deployments per region (ordered as the 'regions' list above)
  deployment_vector: [0.1] # [0.5, 0.5, 0.5, 0.5]

  # Keeping files at the end of the run.
  keep_files: False

#
dispatch:
  include: True
  tech: "ccgt"

# Nuclear
nuclear:
  include: False
  use_ex_cap: True # Whether to include existing cap
  extendable: False
  ramp_rate: 0.01 # for up and down (can go up or down 1O% of the total capacity every time step)

# Storage
storage:
  include: False
  max_hours: 4

# Hydro
phs:
  include: True
  use_ex_cap: True
  extendable: False
  efficiency_store: 0.75
  efficiency_dispatch: 0.75
  cyclic_sof: True
  max_hours: 6

ror:
  include: True
  use_ex_cap: True
  extendable: False
  efficiency: 0.9

sto:
  include: True
  use_ex_cap: True
  extendable: False
  efficiency_dispatch: 0.9
  cyclic_sof: True


# Emissions
co2_emissions:
  global_per_year: 1 #Gt/year
  level_1990: 523.6 # t/GWh
  reduc_from_1990: 0.8 #%
