# Scope parameters
spatial_resolution: 1.0
timeslice: ['2016-01-01T00:00', '2016-01-01T23:00']
regions: ['BENELUX']
technologies: ['wind_offshore']

use_ex_cap: False

# Optimization parameters
formulation: 'complementarity' # Type of problem to be solved.
formulation_params:
  # cap_per_tech: [0.5, 0.5]
  perc_per_region: [0.32]
  time_resolution: 'hour'
  # nb_sites_per_region: [11]
modelling: 'pyomo' # Choice of modelling language.
write_lp: False
