# Config file for various conversion technologies.
wind_onshore:
  converter: 'G3.45'
  resource: 'wind'
  deployment: 'onshore'
  resource_threshold: 5. #m/s
  population_density_threshold_low: 0.
  population_density_threshold_high: 100.
  protected_areas_selection: ['Ia', 'Ib', 'II']
  protected_areas_distance_threshold: 10.
  depth_threshold_low: 0.
  depth_threshold_high: 0.
  altitude_threshold: 1500.
  terrain_slope_threshold: 0.03
  forestry_ratio_threshold: 0.7

wind_offshore:
  converter: 'E-126'
  resource: 'wind'
  deployment: 'offshore'
  resource_threshold: 7. #m/s
  population_density_threshold_low: 0.
  population_density_threshold_high: 100.
  protected_areas_selection: ['Ia', 'Ib', 'II', 'V']
  protected_areas_distance_threshold: 5.
  depth_threshold_low: 5.
  depth_threshold_high: 100.
  altitude_threshold: 0.
  terrain_slope_threshold: 1.
  forestry_ratio_threshold: 1.

wind_floating:
  converter: 'E-126'
  resource: 'wind'
  deployment: 'floating'
  resource_threshold: 9. #m/s
  population_density_threshold_low: 0.
  population_density_threshold_high: 100.
  protected_areas_selection: ['Ia', 'Ib', 'II', 'V']
  protected_areas_distance_threshold: 5.
  depth_threshold_low: 100.
  depth_threshold_high: 990.
  altitude_threshold: 0.
  terrain_slope_threshold: 1.
  forestry_ratio_threshold: 1.

pv_utility:
  converter: 'DEG15MC'
  resource: 'pv'
  deployment: 'utility'
  resource_threshold: 130. #W/m2
  population_density_threshold_low: 0.
  population_density_threshold_high: 100.
  protected_areas_selection: ['Ia', 'Ib', 'II', 'V']
  protected_areas_distance_threshold: 5.
  depth_threshold_low: 0.
  depth_threshold_high: 0.
  altitude_threshold: 2000.
  terrain_slope_threshold: 0.05
  forestry_ratio_threshold: 0.8

pv_residential:
  converter: 'DD06M'
  resource: 'pv'
  deployment: 'residential'
  resource_threshold: 100. #W/m2
  population_density_threshold_low: 10.
  population_density_threshold_high: 999999.
  protected_areas_selection: ['Ia', 'Ib', 'II', 'V']
  protected_areas_distance_threshold: 1.
  depth_threshold_low: 0.
  depth_threshold_high: 0.
  altitude_threshold: 3000.
  terrain_slope_threshold: 1.
  forestry_ratio_threshold: 1.

ccgt:
  efficiency: 0.9

ocgt:
  efficiency: 0.9

nuclear:
  ramp_rate: 0.01 # for up and down (can go up or down 1O% of the total capacity every time step)

phs:
  efficiency_store: 0.75
  efficiency_dispatch: 0.75

ror:
  efficiency: 0.9

sto:
  efficiency_dispatch: 0.9

