# model
keep_lp: True

# solver
solver: 'gurobi'
solver_options:
  gurobi:
    Threads: 0
    Method: 2
    BarHomogeneous: 1
    Crossover: 0
    BarConvTol: 0.0001
  cplex:
    solutiontype: 1
  cbc: 0

# Time
# Start time and end time for slicing the database.
time:
  slice: ['2015-01-01T00:00', '2015-01-10T23:00']
  resolution: 1

# Space
region: "EU"
# add_offshore: False

# RES
res:
  include: True
  # Give which technology should be installed using each strategy
  strategies:
    max: ['wind_offshore']
    comp: []
    no_siting: []
    siting: []
    bus: ['wind_onshore', 'pv_utility', 'pv_residential']

  # For strategy = max or comp
  path: 'EU_wide_off_2015_08'
  resite_nb: 0 # can be multiples of 25
  area_per_site: 2500 #km2
  cap_dens:
     wind_onshore: 3  # MW/km2, assuming 30% max utilization of the entire cell area
     wind_offshore: 6 # MW/km2, assuming 60% max utilization of the entire cell area

  # For strategy = siting or no siting
  # Various data layers to be taken into account in potential site selection.
  spatial_resolution: 0.5
  timeslice: ['2015-01-01T00:00', '2015-01-01T23:00']
  use_ex_cap: True
  limit_max_cap: True
  filtering_layers:
    resource_quality: True
    population_density: True
    protected_areas: False
    bathymetry: True
    orography: True
    forestry: True
    water_mask: True

  # For strategy = siting
  modelling: 'pyomo' # Choice of modelling language. Available: 'gurobipy', 'docplex' and 'pyomo'
  solver: 'gurobi' # Choice of solver. Available: 'gurobi', 'cplex' and 'cbc'
  solver_options:
    gurobi:
      Threads: 0
      Method: 1
    cplex:
      solutiontype: 1
    cbc: 0
  write_lp: False
  write_log: False
  # Type of problem to be solved. Check resite.py for a full list.
  formulation: 'meet_RES_targets_agg' # 'meet_RES_targets_hourly' # 'meet_demand_with_capacity' #
  formulation_params: [0.1] # [0.5, 0.5, 0.5, 0.5]
  # Keeping files at the end of the run.
  keep_files: True

# Conventional generation
dispatch:
  include: True
  tech: "ccgt"

# Nuclear
nuclear:
  include: True
  use_ex_cap: True # Whether to include existing cap
  extendable: False

# Battery
battery:
  include: True
  type: "Li-ion"

# Hydro
phs:
  include: True
  use_ex_cap: True
  extendable: False
  cyclic_sof: True

ror:
  include: True
  use_ex_cap: True
  extendable: False

sto:
  include: True
  use_ex_cap: True
  extendable: False
  cyclic_sof: True

functionalities:
  snsp:
    include: False
    share: 0.65
  curtailment:
    include: True
    strategy: ['technical', 1.] # ['technical', 0.], ['technical', 1.], ['economic', 0.], ['economic', 9999.]

# Emissions
co2_emissions:
  reference_year: 1990 # The only available point now.
  mitigation_factor: 0.0